# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np


print(np.zeros((2, 3)))
print(np.empty((2, 3)))

'''
1.

np.zeros 元素為真實的 0 

np.empty 是接近0的很小的數

2.

np.empty能快速產生隨機接近零的元素 


'''


[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [9]:
# 記得先 Import 正確的套件

import numpy as np

In [11]:
# 參考解答


a = np.random.rand(2, 3)

a = a*100

print(a)
print(np.floor(a)) #去掉小數
print(np.round(a)) # 四捨五入

[[47.9844163   7.43847306 19.81894113]
 [40.12345278 40.57652765 43.34256387]]
[[47.  7. 19.]
 [40. 40. 43.]]
[[48.  7. 20.]
 [40. 41. 43.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [14]:
m = 20
n = 40

a = np.random.rand(2, 3)*(n-m)
b=a+m

print(b)


[[29.24757346 39.15171134 37.3731275 ]
 [27.5437069  24.63990814 34.97770643]]
