# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [1]:
'''
a.sum 在多維下，可以設定軸(Axis)的參數 
sum(a) 是 python 內建的函式，所有型態皆可以用，預設是從 axis = 0 的方向做加總
np.sum(a) 跟 a.sum() 定義在 np 或是 array 底下，輸出結果相同

'''

'\na.sum 在多維下，可以設定軸(Axis)的參數 \nsum(a) 是 python 內建的函式，所有型態皆可以用，預設是從 axis = 0 的方向做加總\nnp.sum(a) 跟 a.sum() 定義在 np 或是 array 底下，輸出結果相同\n\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [3]:
# 記得先 Import 正確的套件

import numpy as np

In [4]:
A = np.random.random((5, 5))

A_normal = (A - A.min()) / (A.max() - A.min())

print(A_normal)

[[0.71728836 0.42127613 0.73715861 0.83457584 0.00260448]
 [0.52682582 0.19168605 0.36572771 0.79990425 0.69008353]
 [0.35985387 0.4667891  0.77670746 0.64386906 0.53697705]
 [0.83454195 0.16514295 1.         0.0427754  0.94336231]
 [0.84706348 0.0886167  0.         0.87987643 0.64034431]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [7]:
B= np.random.random(10)
B[np.argmax(B)]=-1
print(B)

[ 0.69382789 -1.          0.52331168  0.26537328  0.12875018  0.54754606
  0.75908576  0.810093    0.08171483  0.91416858]
