# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [3]:
%timeit -n 10 a = 2

Z + 1


28.6 ns ± 13.6 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


'\nYour Code\n'

In [10]:
%timeit -n 10 a = 2

Z1=[]
for row in Z.flatten():
    Z1.append(row+1)
    
#print(np.array(Z1).reshape(100,100,100))



30 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%timeit -n 10 a = 2

Z2=[]
for d in np.nditer(Z):
    Z2.append(d+1)

print(np.array(Z2).reshape(100,100,100))

30 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[ 7  4  9 ...  3  5  7]
  [ 7  6  8 ...  2  3  4]
  [10  6  8 ...  4  3  3]
  ...
  [ 8 10  1 ...  6  9  7]
  [ 7  6  7 ...  6  8  4]
  [ 7  1 10 ...  7  6  7]]

 [[ 4  3  9 ...  4  9  7]
  [ 9 10  1 ...  2 10  5]
  [ 1  4  6 ...  6 10  4]
  ...
  [ 1  5  5 ...  2  1  9]
  [ 7  6  6 ...  4  6  5]
  [10  8  1 ...  4  2  8]]

 [[ 6  1  4 ...  6  6 10]
  [ 3  4  9 ...  2  2  7]
  [ 7  7  5 ...  7  8  7]
  ...
  [ 7  5  1 ...  3  4  5]
  [ 3  3  3 ...  6  8 10]
  [ 9  6 10 ...  1  7  3]]

 ...

 [[ 5  9  8 ...  2  2 10]
  [ 6  9  3 ...  9  9  5]
  [ 4  3  9 ...  9  3  7]
  ...
  [ 7  4 10 ...  2  7  9]
  [ 5  9  7 ...  6  3  5]
  [ 3  5  6 ...  8  1  4]]

 [[ 3 10  6 ...  8  5  5]
  [10  2  8 ...  7  9  7]
  [ 2 10  7 ...  9  5  5]
  ...
  [ 9  6  4 ...  6  2  4]
  [ 5  7  4 ...  6  5 10]
  [ 8  2 10 ...  7  9  6]]

 [[10  4  7 ...  7  1  4]
  [ 2  1  5 ...  7  3  7]
  [ 9  8  3 ...  3  5  6]
  ...
  [ 2  5 10 ...  9 10

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [22]:

Z = np.random.randint(0,10,50)
print(Z)


[7 9 5 5 4 0 1 9 0 6 2 7 7 3 1 3 6 5 5 2 2 7 5 5 1 0 3 1 9 5 8 0 9 0 9 1 1
 4 5 9 3 2 0 2 3 3 8 3 6 0]


In [23]:
d = np.argmax(np.bincount(Z))
print(d)

5


In [24]:
print(np.where(Z==d))

(array([ 2,  3, 17, 18, 22, 23, 29, 38], dtype=int64),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [26]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))




[3, 6, 5, 7, 3, 1]
[3, 6, 5, 7, 3, 1]
[[8, 9, 4, 7], [5, 4, 8, 6], [0, 3, 8, 6]]
[array([8, 9, 4, 7]), array([5, 4, 8, 6]), array([0, 3, 8, 6])]
[[[5, 4], [7, 5], [5, 6]], [[9, 3], [5, 1], [7, 7]]]
[array([[5, 4],
       [7, 5],
       [5, 6]]), array([[9, 3],
       [5, 1],
       [7, 7]])]


In [27]:
def tolist(iterable):
    list1=[]
    if iterable.ndim==1:
        return list(iterable)
    else :
        for i in iterable:
            list1.append(tolist(i))
            
    return list1
            
        
    '''
    Your Code
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[3, 6, 5, 7, 3, 1]
[[8, 9, 4, 7], [5, 4, 8, 6], [0, 3, 8, 6]]
[[[5, 4], [7, 5], [5, 6]], [[9, 3], [5, 1], [7, 7]]]
